# Generated by Django 4.0 on 2023-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthday_date',
            field=models.DateField(null=True),
        ),
    ]
