# Generated by Django 4.0 on 2023-07-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/quiz/'),
        ),
    ]
