# Generated by Django 4.2.1 on 2023-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
