# Generated by Django 4.2.1 on 2023-06-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_quiz_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
