# Generated by Django 4.0 on 2023-06-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scores',
            name='wrong',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
