# Generated by Django 4.0 on 2023-06-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('category', '0006_scores_correct_scores_wrong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='correct',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='passed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='quiz_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='category.quiz'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='wrong',
            field=models.IntegerField(null=True),
        ),
    ]
