# Generated by Django 4.0 on 2023-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_scores_correct_alter_scores_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='quizdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
