# Generated by Django 4.0 on 2023-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_scores_quizdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='quizdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
