# Generated by Django 4.0 on 2023-06-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('category', '0009_alter_scores_quizdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='category.quiz'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='auth.user'),
        ),
    ]
