# Generated by Django 4.2.1 on 2023-06-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_scores_quiz_id_alter_scores_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='quizdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
